"""Pagination-independent ebook structural models."""

from .analyzer import (
    BookStructuralAnalyzer,
    RunningFurnitureOccurrence,
    StructuralAnalysisResult,
)
from .models import (
    AttributionNode,
    BookDocument,
    CaptionNode,
    ContainerCandidateKind,
    ContainerResolutionCandidate,
    DocumentRelationship,
    DocumentTextSpan,
    FigureNode,
    FlowNode,
    FootnoteNode,
    HeadingNode,
    HeadingRole,
    ImageNode,
    InsetNode,
    InsetRole,
    ListItemNode,
    ListKind,
    ListNode,
    ParagraphNode,
    QuotationNode,
    RelationshipKind,
    SemanticMark,
    SourceFragment,
    VerseLineNode,
    VerseNode,
)

__all__: list[str] = [
    "StructuralAnalysisResult",
    "RunningFurnitureOccurrence",
    "BookStructuralAnalyzer",
    "AttributionNode",
    "BookDocument",
    "CaptionNode",
    "ContainerCandidateKind",
    "ContainerResolutionCandidate",
    "DocumentRelationship",
    "DocumentTextSpan",
    "FigureNode",
    "FlowNode",
    "FootnoteNode",
    "HeadingNode",
    "HeadingRole",
    "ImageNode",
    "InsetNode",
    "InsetRole",
    "ListItemNode",
    "ListKind",
    "ListNode",
    "ParagraphNode",
    "QuotationNode",
    "RelationshipKind",
    "SemanticMark",
    "SourceFragment",
    "VerseLineNode",
    "VerseNode",
]
